[package]
name = "firmware-manager-notify"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[build-dependencies]
markup = "0.4.1"

[dependencies]
err-derive = "0.2"
notify-rust = "4.0"
reqwest = "0.10"
firmware-manager = { path = "../" }
