[package]
name = "firmware-manager"
version = "0.1.1"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[workspace]
members = [ "gtk", "gtk/ffi", "notify", "tools" ]

[build-dependencies]
markup = "0.4.1"

[dependencies]
err-derive = "0.2"
fwupd-dbus = { version = "0.1.1" }
system76-firmware-daemon = { git = "https://github.com/pop-os/system76-firmware" }
slotmap = "0.4"
reqwest = "0.10"
human-sort = "0.2.2"
xdg = "2.2.0"
tokio-udev = "0.1"
tokio = "0.1"
better-panic = "0.2"
futures = "0.1"
log = "0.4"
shrinkwraprs = "0.3"
stream-cancel = "0.4"
users = "0.10"
flume = "0.9.0"
