[package]
name = "firmware-manager-gtk"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[dependencies]
better-panic = "0.2"
cascade = "0.1"
err-derive = "0.2"
gio = "0.9"
glib = "0.10"
gtk = { version = "0.9", features = [ "v3_22" ] }
shrinkwraprs = "0.3"
slotmap = "0.4"
html2runes = "1.0"
gdk = "0.13"
upower_dbus = "0.1"
fern = "0.6"
log = "0.4"
clap = "2.33"
yansi = "0.5"
textwrap = "0.12"
firmware-manager = { path = "../" }
flume = "0.9.0"
